"""Declarative base and shared column conventions.

Two things are centralised here so that every table in the schema agrees:

* A naming convention for constraints and indexes. Without it, Alembic
  autogenerate produces migrations that try to drop unnamed constraints it
  cannot identify, which makes downgrades unreliable.
* Timestamp columns, which every table needs and which must be timezone-aware.
  Storing local time in a system that will run in Switzerland and be reviewed
  against UTC logs is a bug waiting to happen.
"""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Predictable constraint names. Alembic needs these to generate reversible
# migrations; PostgreSQL would otherwise assign names we cannot reference.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def utc_now_column() -> Mapped[dt.datetime]:
    """A timezone-aware timestamp defaulting to the database's current time.

    The default is applied by the database rather than by Python, so rows
    written by migrations, by the workers and by the web application all agree
    on the clock.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class TimestampMixin:
    """Adds ``created_at`` and ``updated_at`` to a model.

    ``updated_at`` is maintained by SQLAlchemy on flush. It is deliberately not
    a database trigger: a trigger would also fire for administrative
    corrections applied directly through Adminer, which would quietly hide the
    fact that a row was edited outside the application.
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key generated by the database.

    UUIDs rather than sequential integers for anything a user or an
    administrator can reference by URL. Sequential identifiers let an observer
    count how many accounts exist and guess neighbouring ones.
    """
    return mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
