"""Where uploaded bytes are written, and how they are named.

Two rules, both structural rather than defensive:

1. **The stored name is generated here.** Nothing derived from the uploaded
   filename ever reaches the path. Directory traversal is therefore not
   something to sanitise; there is no attacker-controlled component to
   traverse with.

2. **Everything lands in one of two directories**, and a resolved path outside
   them is a bug that raises. Quarantine and accepted storage are separate
   trees, so a file awaiting a scan cannot be served by a mistake in a
   different code path.

Files are written with owner-only permissions and no execute bit. The storage
directory should also be mounted `noexec` in production, which the deployment
guide records.
"""

from __future__ import annotations

import os
import pathlib
import secrets
from dataclasses import dataclass

from app.config import Settings, get_settings
from app.observability import get_logger

logger = get_logger(__name__)

# Owner read and write only. An uploaded document is not world-readable, and
# it is never executable.
FILE_MODE = 0o600
DIRECTORY_MODE = 0o700


@dataclass(frozen=True)
class StoredFile:
    """A file written to disk."""

    # Relative to the storage root, so moving the root does not invalidate
    # every row in the database.
    relative_path: str
    byte_size: int
    quarantined: bool

    @property
    def shard(self) -> str:
        return self.relative_path.split("/", 1)[0]


class DocumentStore:
    """Reads and writes uploaded documents."""

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._accepted = pathlib.Path(self._settings.upload_storage_path).resolve()
        self._quarantine = pathlib.Path(self._settings.upload_quarantine_path).resolve()

    def _root(self, quarantined: bool) -> pathlib.Path:
        return self._quarantine if quarantined else self._accepted

    def _resolve(self, relative_path: str, quarantined: bool) -> pathlib.Path:
        """Resolve a stored path, refusing anything outside its root.

        Stored paths are generated by this module, so a value failing this
        check means either a database row was tampered with or there is a bug.
        Either way it must not be served.
        """
        root = self._root(quarantined)
        candidate = (root / relative_path).resolve()
        if not candidate.is_relative_to(root):
            raise ValueError("resolved path escapes the storage root")
        return candidate

    def write(self, data: bytes, *, quarantined: bool = True) -> StoredFile:
        """Write bytes under a generated name.

        New uploads land in quarantine by default. Promotion happens only
        after validation and scanning have both passed, so the default is the
        safe one rather than the convenient one.
        """
        # Sharded by the first two hex characters, so one directory does not
        # accumulate hundreds of thousands of entries.
        token = secrets.token_hex(16)
        relative = f"{token[:2]}/{token}"

        target = self._resolve(relative, quarantined)
        target.parent.mkdir(parents=True, exist_ok=True, mode=DIRECTORY_MODE)

        # Written to a temporary name and renamed, so a partial write is never
        # visible under the final path.
        temporary = target.with_suffix(".partial")
        with open(temporary, "wb") as handle:
            handle.write(data)
        os.chmod(temporary, FILE_MODE)
        temporary.replace(target)

        logger.info(
            "upload.stored",
            quarantined=quarantined,
            bytes=len(data),
            shard=relative.split("/", 1)[0],
        )
        return StoredFile(relative_path=relative, byte_size=len(data), quarantined=quarantined)

    def path_of(self, relative_path: str, *, quarantined: bool) -> pathlib.Path:
        """Return the absolute path of a stored file.

        Needed by the malware scanner, which is an external process and takes a
        path rather than bytes. The same containment check applies, so a
        tampered database row cannot make the scanner read outside the storage
        root.
        """
        return self._resolve(relative_path, quarantined)

    def read(self, relative_path: str, *, quarantined: bool) -> bytes:
        """Read a stored file."""
        return self._resolve(relative_path, quarantined).read_bytes()

    def promote(self, relative_path: str) -> StoredFile:
        """Move a file out of quarantine into accepted storage."""
        source = self._resolve(relative_path, quarantined=True)
        target = self._resolve(relative_path, quarantined=False)
        target.parent.mkdir(parents=True, exist_ok=True, mode=DIRECTORY_MODE)
        source.replace(target)
        logger.info("upload.promoted", shard=relative_path.split("/", 1)[0])
        return StoredFile(
            relative_path=relative_path,
            byte_size=target.stat().st_size,
            quarantined=False,
        )

    def delete(self, relative_path: str, *, quarantined: bool) -> bool:
        """Delete a stored file. Returns whether it existed."""
        path = self._resolve(relative_path, quarantined)
        if not path.exists():
            return False
        path.unlink()
        logger.info("upload.deleted", shard=relative_path.split("/", 1)[0])
        return True

    def exists(self, relative_path: str, *, quarantined: bool) -> bool:
        return self._resolve(relative_path, quarantined).exists()
