"""PDF extraction.

Run against real PDF files generated by reportlab rather than hand-written
byte strings, so the parser is exercised against documents a PDF reader would
also accept. See tests/fixtures/generate.py.

The behaviour that matters most is honest quality reporting. A scan with no
text layer yields nothing, which is obvious. A badly OCRed one yields text
that looks plausible and is wrong, reaches retrieval, and gets cited. Both
have to be detected rather than indexed quietly.
"""

from __future__ import annotations

import pathlib

import pytest

from app.db.models.content import ExtractionQuality
from app.ingest.extract_pdf import extract_pdf

FIXTURES = pathlib.Path(__file__).parent / "fixtures"


def load(name: str) -> bytes:
    path = FIXTURES / name
    if not path.exists():  # pragma: no cover
        pytest.skip(f"fixture {name} missing; run tests/fixtures/generate.py")
    return path.read_bytes()


class TestNormalDocument:
    def test_text_is_extracted(self) -> None:
        result = extract_pdf(load("merkblatt.pdf"))
        assert "innert 14 Tagen" in result.text
        assert "CHF 20.--" in result.text

    def test_page_count_is_correct(self) -> None:
        assert extract_pdf(load("merkblatt.pdf")).page_count == 2

    def test_pages_are_numbered_from_one(self) -> None:
        """One-based, matching what a PDF reader shows the resident."""
        result = extract_pdf(load("merkblatt.pdf"))
        assert [p.number for p in result.pages] == [1, 2]

    def test_text_is_attributed_to_the_right_page(self) -> None:
        """This is the whole point: a citation has to name the page."""
        result = extract_pdf(load("merkblatt.pdf"))
        page_one = next(p for p in result.pages if p.number == 1)
        page_two = next(p for p in result.pages if p.number == 2)
        assert "CHF 20.--" in page_one.text
        assert "CHF 20.--" not in page_two.text
        assert "Mietvertrag" in page_two.text

    def test_metadata_is_read(self) -> None:
        result = extract_pdf(load("merkblatt.pdf"))
        assert result.title == "Merkblatt Anmeldung"
        assert result.author == "Kanton Zug"

    def test_upper_case_headings_are_detected(self) -> None:
        result = extract_pdf(load("merkblatt.pdf"))
        page_two = next(p for p in result.pages if p.number == 2)
        assert page_two.section_path
        assert "UNTERLAGEN" in page_two.section_path[0]

    def test_quality_is_good(self) -> None:
        assert extract_pdf(load("merkblatt.pdf")).quality is ExtractionQuality.GOOD


class TestQualityReporting:
    def test_a_scan_with_no_text_layer_is_flagged(self) -> None:
        result = extract_pdf(load("scan_no_text_layer.pdf"))
        assert result.quality is ExtractionQuality.FAILED
        assert result.needs_ocr
        assert any("no_text_layer" in note for note in result.notes)

    def test_an_encrypted_document_is_refused_not_attacked(self) -> None:
        result = extract_pdf(load("encrypted.pdf"))
        assert result.encrypted
        assert result.quality is ExtractionQuality.FAILED
        assert any("encrypted" in note or "undecryptable" in note for note in result.notes)


class TestMalformedInput:
    def test_a_non_pdf_is_reported_not_raised(self) -> None:
        result = extract_pdf(b"<html><body>not a pdf</body></html>")
        assert result.quality is ExtractionQuality.FAILED
        assert any("not_a_pdf" in note for note in result.notes)

    def test_a_zip_renamed_as_pdf_is_refused(self) -> None:
        """The fetcher detects this too; the parser must not rely on that."""
        result = extract_pdf(b"PK\x03\x04" + b"\x00" * 200)
        assert result.quality is ExtractionQuality.FAILED

    def test_truncated_pdf_is_reported_not_raised(self) -> None:
        """A crawl run must not stop because of one corrupt file."""
        truncated = load("merkblatt.pdf")[:400]
        result = extract_pdf(truncated)
        assert result.quality is ExtractionQuality.FAILED
        assert result.notes

    def test_empty_input_is_reported(self) -> None:
        assert extract_pdf(b"").quality is ExtractionQuality.FAILED


class TestActiveContent:
    def test_a_clean_document_reports_no_active_content(self) -> None:
        result = extract_pdf(load("merkblatt.pdf"))
        # reportlab may emit an AcroForm dictionary; anything beyond form
        # fields would be a finding.
        assert "javascript" not in result.active_content
        assert "launch_action" not in result.active_content
        assert "embedded_files" not in result.active_content

    def test_javascript_in_the_catalog_is_detected(self) -> None:
        """Detected, never executed. pypdf parses structure and runs nothing."""
        source = load("merkblatt.pdf")
        # Inject a Names/JavaScript entry into the catalog dictionary.
        hostile = source.replace(b"/Type /Catalog", b"/Names<</JavaScript 1 0 R>>/Type /Catalog", 1)
        result = extract_pdf(hostile)
        # Either the finding is reported, or the file no longer parses. Both
        # are acceptable; silently indexing it is not.
        assert (
            "javascript" in result.active_content
            or result.quality is ExtractionQuality.FAILED
            or "active_content_scan_incomplete" in result.active_content
        )


class TestFilenameFallback:
    def test_filename_is_used_when_the_pdf_has_no_title(self) -> None:
        """A poor title beats an empty citation label."""
        source = load("scan_no_text_layer.pdf")
        result = extract_pdf(source, filename="uploads/Gebuehren_2026.pdf")
        assert result.title == "Gebuehren 2026"
